// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartLighting.proto

package ds.service1;

public interface autoLightsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.autoLightsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool autoLightsOutput = 1;</code>
   */
  boolean getAutoLightsOutput();

  /**
   * <code>string dimLevels = 2;</code>
   */
  java.lang.String getDimLevels();
  /**
   * <code>string dimLevels = 2;</code>
   */
  com.google.protobuf.ByteString
      getDimLevelsBytes();
}
