// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartLighting.proto

package ds.service1;

public interface autoLightsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.autoLightsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool autoLightsInput = 1;</code>
   */
  boolean getAutoLightsInput();
}
