// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartLighting.proto

package ds.service1;

public interface lightMusicRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.lightMusicRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool lightMusicInput = 1;</code>
   */
  boolean getLightMusicInput();
}
