// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartLighting.proto

package ds.service1;

/**
 * Protobuf type {@code service1.lightRequest}
 */
public  final class lightRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:service1.lightRequest)
    lightRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use lightRequest.newBuilder() to construct.
  private lightRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private lightRequest() {
    brightnessInput_ = 0;
    lightOn_ = false;
    colour_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private lightRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            brightnessInput_ = input.readInt32();
            break;
          }
          case 16: {

            lightOn_ = input.readBool();
            break;
          }
          case 24: {

            colour_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.service1.Service1Impl.internal_static_service1_lightRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.service1.Service1Impl.internal_static_service1_lightRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.service1.lightRequest.class, ds.service1.lightRequest.Builder.class);
  }

  public static final int BRIGHTNESSINPUT_FIELD_NUMBER = 1;
  private int brightnessInput_;
  /**
   * <code>int32 brightnessInput = 1;</code>
   */
  public int getBrightnessInput() {
    return brightnessInput_;
  }

  public static final int LIGHTON_FIELD_NUMBER = 2;
  private boolean lightOn_;
  /**
   * <code>bool lightOn = 2;</code>
   */
  public boolean getLightOn() {
    return lightOn_;
  }

  public static final int COLOUR_FIELD_NUMBER = 3;
  private int colour_;
  /**
   * <code>int32 colour = 3;</code>
   */
  public int getColour() {
    return colour_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (brightnessInput_ != 0) {
      output.writeInt32(1, brightnessInput_);
    }
    if (lightOn_ != false) {
      output.writeBool(2, lightOn_);
    }
    if (colour_ != 0) {
      output.writeInt32(3, colour_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (brightnessInput_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, brightnessInput_);
    }
    if (lightOn_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, lightOn_);
    }
    if (colour_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, colour_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.service1.lightRequest)) {
      return super.equals(obj);
    }
    ds.service1.lightRequest other = (ds.service1.lightRequest) obj;

    boolean result = true;
    result = result && (getBrightnessInput()
        == other.getBrightnessInput());
    result = result && (getLightOn()
        == other.getLightOn());
    result = result && (getColour()
        == other.getColour());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BRIGHTNESSINPUT_FIELD_NUMBER;
    hash = (53 * hash) + getBrightnessInput();
    hash = (37 * hash) + LIGHTON_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getLightOn());
    hash = (37 * hash) + COLOUR_FIELD_NUMBER;
    hash = (53 * hash) + getColour();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.service1.lightRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.service1.lightRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.service1.lightRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.service1.lightRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.service1.lightRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.service1.lightRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.service1.lightRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.service1.lightRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.service1.lightRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.service1.lightRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.service1.lightRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.service1.lightRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.service1.lightRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code service1.lightRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:service1.lightRequest)
      ds.service1.lightRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.service1.Service1Impl.internal_static_service1_lightRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.service1.Service1Impl.internal_static_service1_lightRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.service1.lightRequest.class, ds.service1.lightRequest.Builder.class);
    }

    // Construct using ds.service1.lightRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      brightnessInput_ = 0;

      lightOn_ = false;

      colour_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.service1.Service1Impl.internal_static_service1_lightRequest_descriptor;
    }

    @java.lang.Override
    public ds.service1.lightRequest getDefaultInstanceForType() {
      return ds.service1.lightRequest.getDefaultInstance();
    }

    @java.lang.Override
    public ds.service1.lightRequest build() {
      ds.service1.lightRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.service1.lightRequest buildPartial() {
      ds.service1.lightRequest result = new ds.service1.lightRequest(this);
      result.brightnessInput_ = brightnessInput_;
      result.lightOn_ = lightOn_;
      result.colour_ = colour_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.service1.lightRequest) {
        return mergeFrom((ds.service1.lightRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.service1.lightRequest other) {
      if (other == ds.service1.lightRequest.getDefaultInstance()) return this;
      if (other.getBrightnessInput() != 0) {
        setBrightnessInput(other.getBrightnessInput());
      }
      if (other.getLightOn() != false) {
        setLightOn(other.getLightOn());
      }
      if (other.getColour() != 0) {
        setColour(other.getColour());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.service1.lightRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.service1.lightRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int brightnessInput_ ;
    /**
     * <code>int32 brightnessInput = 1;</code>
     */
    public int getBrightnessInput() {
      return brightnessInput_;
    }
    /**
     * <code>int32 brightnessInput = 1;</code>
     */
    public Builder setBrightnessInput(int value) {
      
      brightnessInput_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 brightnessInput = 1;</code>
     */
    public Builder clearBrightnessInput() {
      
      brightnessInput_ = 0;
      onChanged();
      return this;
    }

    private boolean lightOn_ ;
    /**
     * <code>bool lightOn = 2;</code>
     */
    public boolean getLightOn() {
      return lightOn_;
    }
    /**
     * <code>bool lightOn = 2;</code>
     */
    public Builder setLightOn(boolean value) {
      
      lightOn_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool lightOn = 2;</code>
     */
    public Builder clearLightOn() {
      
      lightOn_ = false;
      onChanged();
      return this;
    }

    private int colour_ ;
    /**
     * <code>int32 colour = 3;</code>
     */
    public int getColour() {
      return colour_;
    }
    /**
     * <code>int32 colour = 3;</code>
     */
    public Builder setColour(int value) {
      
      colour_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 colour = 3;</code>
     */
    public Builder clearColour() {
      
      colour_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:service1.lightRequest)
  }

  // @@protoc_insertion_point(class_scope:service1.lightRequest)
  private static final ds.service1.lightRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.service1.lightRequest();
  }

  public static ds.service1.lightRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<lightRequest>
      PARSER = new com.google.protobuf.AbstractParser<lightRequest>() {
    @java.lang.Override
    public lightRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new lightRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<lightRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<lightRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.service1.lightRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

