// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartLighting.proto

package ds.service1;

public interface lightMusicResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.lightMusicResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool lightMusicOutput = 1;</code>
   */
  boolean getLightMusicOutput();
}
