// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartLighting.proto

package ds.service1;

public interface lightResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.lightResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 brightnessOutput = 2;</code>
   */
  int getBrightnessOutput();

  /**
   * <code>bool lightOff = 1;</code>
   */
  boolean getLightOff();

  /**
   * <code>int32 colour = 3;</code>
   */
  int getColour();
}
