// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartLighting.proto

package ds.service1;

public interface lightRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.lightRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 brightnessInput = 1;</code>
   */
  int getBrightnessInput();

  /**
   * <code>bool lightOn = 2;</code>
   */
  boolean getLightOn();

  /**
   * <code>int32 colour = 3;</code>
   */
  int getColour();
}
