// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartLighting.proto

package ds.service1;

/**
 * Protobuf type {@code service1.lightResponse}
 */
public  final class lightResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:service1.lightResponse)
    lightResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use lightResponse.newBuilder() to construct.
  private lightResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private lightResponse() {
    brightnessOutput_ = 0;
    lightOff_ = false;
    colour_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private lightResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            lightOff_ = input.readBool();
            break;
          }
          case 16: {

            brightnessOutput_ = input.readInt32();
            break;
          }
          case 24: {

            colour_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.service1.Service1Impl.internal_static_service1_lightResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.service1.Service1Impl.internal_static_service1_lightResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.service1.lightResponse.class, ds.service1.lightResponse.Builder.class);
  }

  public static final int BRIGHTNESSOUTPUT_FIELD_NUMBER = 2;
  private int brightnessOutput_;
  /**
   * <code>int32 brightnessOutput = 2;</code>
   */
  public int getBrightnessOutput() {
    return brightnessOutput_;
  }

  public static final int LIGHTOFF_FIELD_NUMBER = 1;
  private boolean lightOff_;
  /**
   * <code>bool lightOff = 1;</code>
   */
  public boolean getLightOff() {
    return lightOff_;
  }

  public static final int COLOUR_FIELD_NUMBER = 3;
  private int colour_;
  /**
   * <code>int32 colour = 3;</code>
   */
  public int getColour() {
    return colour_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (lightOff_ != false) {
      output.writeBool(1, lightOff_);
    }
    if (brightnessOutput_ != 0) {
      output.writeInt32(2, brightnessOutput_);
    }
    if (colour_ != 0) {
      output.writeInt32(3, colour_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (lightOff_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, lightOff_);
    }
    if (brightnessOutput_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, brightnessOutput_);
    }
    if (colour_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, colour_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.service1.lightResponse)) {
      return super.equals(obj);
    }
    ds.service1.lightResponse other = (ds.service1.lightResponse) obj;

    boolean result = true;
    result = result && (getBrightnessOutput()
        == other.getBrightnessOutput());
    result = result && (getLightOff()
        == other.getLightOff());
    result = result && (getColour()
        == other.getColour());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BRIGHTNESSOUTPUT_FIELD_NUMBER;
    hash = (53 * hash) + getBrightnessOutput();
    hash = (37 * hash) + LIGHTOFF_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getLightOff());
    hash = (37 * hash) + COLOUR_FIELD_NUMBER;
    hash = (53 * hash) + getColour();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.service1.lightResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.service1.lightResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.service1.lightResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.service1.lightResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.service1.lightResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.service1.lightResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.service1.lightResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.service1.lightResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.service1.lightResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.service1.lightResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.service1.lightResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.service1.lightResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.service1.lightResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code service1.lightResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:service1.lightResponse)
      ds.service1.lightResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.service1.Service1Impl.internal_static_service1_lightResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.service1.Service1Impl.internal_static_service1_lightResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.service1.lightResponse.class, ds.service1.lightResponse.Builder.class);
    }

    // Construct using ds.service1.lightResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      brightnessOutput_ = 0;

      lightOff_ = false;

      colour_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.service1.Service1Impl.internal_static_service1_lightResponse_descriptor;
    }

    @java.lang.Override
    public ds.service1.lightResponse getDefaultInstanceForType() {
      return ds.service1.lightResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ds.service1.lightResponse build() {
      ds.service1.lightResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.service1.lightResponse buildPartial() {
      ds.service1.lightResponse result = new ds.service1.lightResponse(this);
      result.brightnessOutput_ = brightnessOutput_;
      result.lightOff_ = lightOff_;
      result.colour_ = colour_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.service1.lightResponse) {
        return mergeFrom((ds.service1.lightResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.service1.lightResponse other) {
      if (other == ds.service1.lightResponse.getDefaultInstance()) return this;
      if (other.getBrightnessOutput() != 0) {
        setBrightnessOutput(other.getBrightnessOutput());
      }
      if (other.getLightOff() != false) {
        setLightOff(other.getLightOff());
      }
      if (other.getColour() != 0) {
        setColour(other.getColour());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.service1.lightResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.service1.lightResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int brightnessOutput_ ;
    /**
     * <code>int32 brightnessOutput = 2;</code>
     */
    public int getBrightnessOutput() {
      return brightnessOutput_;
    }
    /**
     * <code>int32 brightnessOutput = 2;</code>
     */
    public Builder setBrightnessOutput(int value) {
      
      brightnessOutput_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 brightnessOutput = 2;</code>
     */
    public Builder clearBrightnessOutput() {
      
      brightnessOutput_ = 0;
      onChanged();
      return this;
    }

    private boolean lightOff_ ;
    /**
     * <code>bool lightOff = 1;</code>
     */
    public boolean getLightOff() {
      return lightOff_;
    }
    /**
     * <code>bool lightOff = 1;</code>
     */
    public Builder setLightOff(boolean value) {
      
      lightOff_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool lightOff = 1;</code>
     */
    public Builder clearLightOff() {
      
      lightOff_ = false;
      onChanged();
      return this;
    }

    private int colour_ ;
    /**
     * <code>int32 colour = 3;</code>
     */
    public int getColour() {
      return colour_;
    }
    /**
     * <code>int32 colour = 3;</code>
     */
    public Builder setColour(int value) {
      
      colour_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 colour = 3;</code>
     */
    public Builder clearColour() {
      
      colour_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:service1.lightResponse)
  }

  // @@protoc_insertion_point(class_scope:service1.lightResponse)
  private static final ds.service1.lightResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.service1.lightResponse();
  }

  public static ds.service1.lightResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<lightResponse>
      PARSER = new com.google.protobuf.AbstractParser<lightResponse>() {
    @java.lang.Override
    public lightResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new lightResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<lightResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<lightResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.service1.lightResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

