// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartLighting.proto

package ds.service1;

public final class Service1Impl {
  private Service1Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_lightRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_lightRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_lightResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_lightResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_autoLightsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_autoLightsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_autoLightsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_autoLightsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_lightMusicRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_lightMusicRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_lightMusicResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_lightMusicResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023SmartLighting.proto\022\010service1\"H\n\014light" +
      "Request\022\027\n\017brightnessInput\030\001 \001(\005\022\017\n\007ligh" +
      "tOn\030\002 \001(\010\022\016\n\006colour\030\003 \001(\005\"K\n\rlightRespon" +
      "se\022\030\n\020brightnessOutput\030\002 \001(\005\022\020\n\010lightOff" +
      "\030\001 \001(\010\022\016\n\006colour\030\003 \001(\005\",\n\021autoLightsRequ" +
      "est\022\027\n\017autoLightsInput\030\001 \001(\010\".\n\022autoLigh" +
      "tsResponse\022\030\n\020autoLightsOutput\030\001 \001(\010\",\n\021" +
      "lightMusicRequest\022\027\n\017lightMusicInput\030\001 \001" +
      "(\010\".\n\022lightMusicResponse\022\030\n\020lightMusicOu" +
      "tput\030\001 \001(\0102\355\001\n\rSmartLighting\022D\n\013smartLig" +
      "hts\022\026.service1.lightRequest\032\027.service1.l" +
      "ightResponse\"\000(\0010\001\022I\n\nautoLights\022\033.servi" +
      "ce1.autoLightsRequest\032\034.service1.autoLig" +
      "htsResponse\"\000\022K\n\nlightMusic\022\033.service1.l" +
      "ightMusicRequest\032\034.service1.lightMusicRe" +
      "sponse\"\0000\001B\035\n\013ds.service1B\014Service1ImplP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service1_lightRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service1_lightRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_lightRequest_descriptor,
        new java.lang.String[] { "BrightnessInput", "LightOn", "Colour", });
    internal_static_service1_lightResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service1_lightResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_lightResponse_descriptor,
        new java.lang.String[] { "BrightnessOutput", "LightOff", "Colour", });
    internal_static_service1_autoLightsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service1_autoLightsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_autoLightsRequest_descriptor,
        new java.lang.String[] { "AutoLightsInput", });
    internal_static_service1_autoLightsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service1_autoLightsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_autoLightsResponse_descriptor,
        new java.lang.String[] { "AutoLightsOutput", });
    internal_static_service1_lightMusicRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_service1_lightMusicRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_lightMusicRequest_descriptor,
        new java.lang.String[] { "LightMusicInput", });
    internal_static_service1_lightMusicResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_service1_lightMusicResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_lightMusicResponse_descriptor,
        new java.lang.String[] { "LightMusicOutput", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
