// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartLighting.proto

package ds.service1;

public final class Service1Impl {
  private Service1Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_lightRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_lightRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_lightResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_lightResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_autoLightsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_autoLightsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_autoLightsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_autoLightsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_lightMusicRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_lightMusicRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_lightMusicResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_lightMusicResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023SmartLighting.proto\022\010service1\"H\n\014light" +
      "Request\022\027\n\017brightnessInput\030\001 \001(\005\022\017\n\007ligh" +
      "tOn\030\002 \001(\010\022\016\n\006colour\030\003 \001(\005\"K\n\rlightRespon" +
      "se\022\030\n\020brightnessOutput\030\002 \001(\005\022\020\n\010lightOff" +
      "\030\001 \001(\010\022\016\n\006colour\030\003 \001(\005\",\n\021autoLightsRequ" +
      "est\022\027\n\017autoLightsInput\030\001 \001(\010\"A\n\022autoLigh" +
      "tsResponse\022\030\n\020autoLightsOutput\030\001 \001(\010\022\021\n\t" +
      "dimLevels\030\002 \001(\t\",\n\021lightMusicRequest\022\027\n\017" +
      "lightMusicInput\030\001 \001(\010\".\n\022lightMusicRespo" +
      "nse\022\030\n\020lightMusicOutput\030\001 \001(\0102\355\001\n\rSmartL" +
      "ighting\022D\n\013smartLights\022\026.service1.lightR" +
      "equest\032\027.service1.lightResponse\"\000(\0010\001\022I\n" +
      "\nautoLights\022\033.service1.autoLightsRequest" +
      "\032\034.service1.autoLightsResponse\"\000\022K\n\nligh" +
      "tMusic\022\033.service1.lightMusicRequest\032\034.se" +
      "rvice1.lightMusicResponse\"\0000\001B\035\n\013ds.serv" +
      "ice1B\014Service1ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service1_lightRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service1_lightRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_lightRequest_descriptor,
        new java.lang.String[] { "BrightnessInput", "LightOn", "Colour", });
    internal_static_service1_lightResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service1_lightResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_lightResponse_descriptor,
        new java.lang.String[] { "BrightnessOutput", "LightOff", "Colour", });
    internal_static_service1_autoLightsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service1_autoLightsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_autoLightsRequest_descriptor,
        new java.lang.String[] { "AutoLightsInput", });
    internal_static_service1_autoLightsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service1_autoLightsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_autoLightsResponse_descriptor,
        new java.lang.String[] { "AutoLightsOutput", "DimLevels", });
    internal_static_service1_lightMusicRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_service1_lightMusicRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_lightMusicRequest_descriptor,
        new java.lang.String[] { "LightMusicInput", });
    internal_static_service1_lightMusicResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_service1_lightMusicResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_lightMusicResponse_descriptor,
        new java.lang.String[] { "LightMusicOutput", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
