// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartMangement.proto

package ds.service2;

public interface qRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.qRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string qOrder = 1;</code>
   */
  java.lang.String getQOrder();
  /**
   * <code>string qOrder = 1;</code>
   */
  com.google.protobuf.ByteString
      getQOrderBytes();

  /**
   * <code>int32 time = 2;</code>
   */
  int getTime();
}
