// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartMangement.proto

package ds.service2;

public interface qResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.qResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string qSuccessful = 1;</code>
   */
  java.lang.String getQSuccessful();
  /**
   * <code>string qSuccessful = 1;</code>
   */
  com.google.protobuf.ByteString
      getQSuccessfulBytes();
}
