// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartMangement.proto

package ds.service2;

public interface TableRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.TableRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 tableInput = 1;</code>
   */
  int getTableInput();

  /**
   * <code>double timeInput = 2;</code>
   */
  double getTimeInput();
}
