// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartMangement.proto

package ds.service2;

public interface TableResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.TableResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tableOutput = 1;</code>
   */
  java.lang.String getTableOutput();
  /**
   * <code>string tableOutput = 1;</code>
   */
  com.google.protobuf.ByteString
      getTableOutputBytes();
}
