// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartMangement.proto

package ds.service2;

public interface viewRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.viewRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string totalOrders = 1;</code>
   */
  java.lang.String getTotalOrders();
  /**
   * <code>string totalOrders = 1;</code>
   */
  com.google.protobuf.ByteString
      getTotalOrdersBytes();
}
