// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartMangement.proto

package ds.service2;

public interface viewResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.viewResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string bookingsTotal = 1;</code>
   */
  java.lang.String getBookingsTotal();
  /**
   * <code>string bookingsTotal = 1;</code>
   */
  com.google.protobuf.ByteString
      getBookingsTotalBytes();
}
