// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartTill.proto

package ds.service3;

public interface seatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.seatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string seats = 1;</code>
   */
  java.lang.String getSeats();
  /**
   * <code>string seats = 1;</code>
   */
  com.google.protobuf.ByteString
      getSeatsBytes();
}
