// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartTill.proto

package ds.service3;

public interface seatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.seatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string totalSeats = 1;</code>
   */
  java.lang.String getTotalSeats();
  /**
   * <code>string totalSeats = 1;</code>
   */
  com.google.protobuf.ByteString
      getTotalSeatsBytes();
}
