// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartTill.proto

package ds.service3;

public final class Service3Impl {
  private Service3Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_tillRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_tillRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_tillResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_tillResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_seatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_seatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_seatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_seatResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017SmartTill.proto\022\010service3\"C\n\013tillReque" +
      "st\022\022\n\norderInput\030\001 \001(\t\022\017\n\007seatCol\030\002 \001(\005\022" +
      "\017\n\007seatRow\030\003 \001(\005\")\n\014tillResponse\022\031\n\021tota" +
      "lOrdersOutput\030\001 \001(\t\" \n\013seatRequest\022\021\n\tvi" +
      "ewSeats\030\001 \001(\t\"\"\n\014seatResponse\022\022\n\nseatOut" +
      "put\030\001 \001(\t2\215\001\n\tSmartTill\022@\n\tsmartTill\022\025.s" +
      "ervice3.tillRequest\032\026.service3.tillRespo" +
      "nse\"\000(\0010\001\022>\n\013seatManager\022\025.service3.seat" +
      "Request\032\026.service3.seatResponse\"\000B\035\n\013ds." +
      "service3B\014Service3ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service3_tillRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service3_tillRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_tillRequest_descriptor,
        new java.lang.String[] { "OrderInput", "SeatCol", "SeatRow", });
    internal_static_service3_tillResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service3_tillResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_tillResponse_descriptor,
        new java.lang.String[] { "TotalOrdersOutput", });
    internal_static_service3_seatRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service3_seatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_seatRequest_descriptor,
        new java.lang.String[] { "ViewSeats", });
    internal_static_service3_seatResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service3_seatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_seatResponse_descriptor,
        new java.lang.String[] { "SeatOutput", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
