// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartTill.proto

package ds.service3;

public interface tillRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.tillRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string orderInput = 1;</code>
   */
  java.lang.String getOrderInput();
  /**
   * <code>string orderInput = 1;</code>
   */
  com.google.protobuf.ByteString
      getOrderInputBytes();
}
