// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartTill.proto

package ds.service3;

public interface tillRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.tillRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string orderInput = 1;</code>
   */
  java.lang.String getOrderInput();
  /**
   * <code>string orderInput = 1;</code>
   */
  com.google.protobuf.ByteString
      getOrderInputBytes();

  /**
   * <code>int32 seatCol = 2;</code>
   */
  int getSeatCol();

  /**
   * <code>int32 seatRow = 3;</code>
   */
  int getSeatRow();
}
