// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartTill.proto

package ds.service3;

public interface tillResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.tillResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string totalOrdersOutput = 1;</code>
   */
  java.lang.String getTotalOrdersOutput();
  /**
   * <code>string totalOrdersOutput = 1;</code>
   */
  com.google.protobuf.ByteString
      getTotalOrdersOutputBytes();
}
